[package]
name = "submarine-rs"
version = "0.12.0"
description = "Toolkit for subtitle processing"
edition = "2024"
authors = ["Eugene Lebedev <eugene.0x90@gmail.com>"]
homepage = "https://github.com/lebe-dev/submarine"
repository = "https://github.com/lebe-dev/submarine"
readme = "README.md"
keywords = ["subtitle", "subrip"]
categories = ["encoding"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[features]
default = ["cli"]
cli = ["clap"]

[[bin]]
name = "sm"
path = "src/bin/cli/main.rs"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"

nutype = { version = "0.5", features = ["serde"] }

clap = { version = "4.5.53", features = ["derive"], optional = true}

chrono = "0.4.42"

csv = "1.4.0"

tera = "1.20.1"
glob = "0.3"

log = "0.4.29"
log4rs = "1.4.0"

ratatui = "0.30.0"
crossterm = "0.28"
rand = "0.8"

[dev-dependencies]
tempfile = "3.8"
